import { useEffect } from "react";
import Head from "next/head";
import AOS from "aos";
import "aos/dist/aos.css";
import HeroSection from "../../components/HeroSection";
import SpecialServices from "../../components/SpecialServices";
import CoursesForHomeSection from "../../components/CoursesForHomeSection";
import * as fs from "fs";

export async function getServerSideProps() {
  try {
    let files = fs.readdirSync("data", "utf-8"); // read the 'data' directory
    const updated_files = files.filter((file) => file !== "services.json"); // removing the services.json file cause we don't need this in corses section
    let courses = []; //* make an empty array to append all the data after reading 'updated_files'

    updated_files.forEach((file) => {
      let file_data = fs.readFileSync(`data/${file}`, "utf-8"); // read the files form 'data' directory
      JSON.parse(file_data).forEach((item) => {
        courses.push(item); // add all the data to the 'data' array
      });
    });

    let res_services = await fs.readFileSync("data/services.json", "utf-8");
    let services = JSON.parse(res_services);

    return {
      props: { services, courses },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { services: [], courses: [] },
    };
  }
}

export default function Home({ services, courses }) {
  useEffect(() => {
    AOS.init({
      offset: 200, // Start animation 200px from the top of the viewport
      duration: 600, // Animation duration
      easing: "ease-out-cubic", // Animation easing
      delay: 100, // Delay between animations
      once: true, // Only animate elements once
    });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#ff0080" />
        <meta name="msapplication-TileColor" content="#ff0080" />
        <meta name="apple-mobile-web-app-status-bar-style" content="#ff0080" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection />
        <SpecialServices data={services} />
        <CoursesForHomeSection data={courses} />
      </main>
    </>
  );
}
